# Downscale to limit CPU/memory (change to ~1200 for more detail)
resize_to: 1024

# Robust, slower but CPU-friendly SIFT
feature_type: SIFT
feature_root: features
feature_process_size: 1024
feature_min_frames: 2000          # cap feature count
feature_max_frames: 4000

# Good for ordered arm photos (sequential matching)
matching_order_neighbors: 8
matching_gps_neighbors: 0
matching_time_neighbors: 0
matcher_type: FLANN
# If images contain EXIF focal length, leave this off; otherwise:
use_exif_size: true

# Triangulation/dense parameters (kept conservative)
min_track_length: 2
bundle_interval: 0
depthmaps_min_consistent_views: 2
depthmap_resolution: 640
depthmap_method: PATCH_MATCH

